# Общие сведения {.unnumbered}

:::{.callout-note}
*Документация версии {{< var docs_version >}}, написана для библиотеки genesis версии {{< var genesis_version >}}.*
:::

**Основное назначение библиотеки** - предоставление пользователю возможностей по решению задач пространственной оптимизации подразделений пожарной охраны, а также возможностей программной исследовательской платформы для изучения и разработки методов решения таких задач.

Библиотека решает следующие задачи определения наилучшей дислокации подразделений пожарной охраны:

1. Задача определения наилучшей дислокации единственного подразделения (далее – **BLP**, от англ. *Best Location Problem*)
2. Задача определения наилучшей дислокации множества подразделений (**MCLP** – *Maximal Covering Location Problem*)
3. Задача определения количества подразделений при наилучшей дислокации (**LSCP** – *Location Set Covering Problem*)

Помимо названного, библиотека может решать ряд дополнительных задач:

1. Моделирование и анализ параметров прибытия подразделений пожарной охраны
2. Определение оптимальных границ районов выезда подразделений пожарной охраны




Основной функционал genesis основан на библиотеке osmnx [@boeing_osmnx_2017].




