# Инструменты обработки используемые в расчетах

Модуль `genesis.tools`


## Функции

### `get_all_neighbor_nodes(G: nx.Graph, node: int) → list`

Возвращает полный список всех соседних узлов.

#### Аргументы

- `G` (networkx.MultiDiGraph)  
  Граф улично-дорожной сети
- `node` (int)  
  Узел графа

---

### `multi_source_dijkstra_reversed(G, sources, **kwargs) → Any`

Алгоритм расчета кратчайших маршрутов в точки `source`  
с использованием алгоритма Дейкстры  
в реализации `nx.multi_source_dijkstra`.

#### Аргументы

- `G` (networkx.MultiDiGraph)  
  Граф улично-дорожной сети
- `sources` (list)  
  Список точек откуда начинается расчет
- `**kwargs` (Any)  
  Дополнительные аргументы для алгоритма Дейкстры

---

### `list_dict_concat(a: list | dict, b: list | dict) → list | dict`

Корректно склеивает между собой списки и словари.  
При условии, что аргумент `a` и аргумент `b` одного типа.

#### Аргументы

- `a`, `b` (list | dict)  
  Аргументы которые следует склеить между собой

---

### `k_v_dict(d, f=min)`

Получаем номер ключа в словаре которому соответствует значение с  
минимальным/максимальным/средним и т.д. значением, в зависимости  
от функции `f`.

Самый быстрый способ.

#### Аргументы

- `d` (dict)  
  Словарь в котором ищем значение
- `f` (callable)  
  Функция для получения значения

---

### `get_dict_key(dictionary, value)`

Получение ключа в словаре по значению

#### Аргументы

- `dictionary` (dict)  
  Словарь в котором ищем значение  
- `value` (Any)  

---

### `get_duplicates_list(seq)`

Получение списка дублирующихся во входящем списке значений

#### Аргументы

- `seq` (list)  
  Список значений