# Подготовка основных типов исходных данных

Для большинства задач расчета параметров прибытия подразделений пожарной охраны и определения оптимальной дислокации в большинстве случаев достаточно следующих данных:

* Границы населенных пунктов и территорий
* Граф улично-дорожной сети
* Сведения о зданиях и сооружениях
* Сведения о подразделениях пожарной охраны

Подготовка исходных данных осуществляется в два этапа:

1. Получение и предварительная обработка
2. Подготовка рабочих наборов данных

Получение и предварительная обработка данных выполняются за счет получения пространственных данных из открытых источников. Основным источником пространственных данных о населенных пунктах рекомендуется рассматривать сервис [OpenStreetMap](https://www.openstreetmap.org/).

Некоторые данные, такие как, места размещения ПСЧ в открытом доступе либо отсутствуют, либо являются неполными или ошибочными. Такие данные лучше заполнять на основе имеющихся в расположении пользователей данных.

Окончательная подготовка рабочих наборов данных выполняется как правило в приложении QGIS и заключается в сверке полученных данных с реальностью - добавление отсутствующих данных, исправление ошибочных и обогащение дополнительными данными.

Ниже описан процесс получения данных с использованием средств языка программирования `Python`.